### ISSUE TITLE
[5%] Provide the data schema in blockchain

### ISSUE THREAD

**Issue by BITWN** [CCPX-system/CCPX-blockchain#4]
data schema

**Comment by ShiKaize** [comment]
b4b28d3
加了一些返回代码
修改了结构
9e7a191

**Comment by BITWN** [comment]
1 parent 558ec34 commit 113075cf09ac08aa5de8c8bbbf2967d64f5ac41d

**Comment by BITWN** [comment]
sprint 5:
9e7a191
